version: 0.1
phases:
  install:
    commands:
      - npm install time
      - aws cloudformation package --template /template/apiTemplate.json --s3-bucket artifact-manas
                                   --output json > NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml
