version: 0.1
phases:
  install:
    commands:
      - sudo pip install awscli
  build:
    commands:
      - aws --version
      - aws cloudformation package --template-file ./template/apiTemplate.json --s3-bucket artifact-manas
                                   --output-template-file NewSamTemplate.json
artifacts:
  type: zip
  files:
    - NewSamTemplate.json
